server:
  port: 8080

spring:
  datasource:
    name: BreadManageSystem
    url: jdbc:mysql://localhost:3306/BreadManageSystem?serverTimezone=UTC
    username: root
    password: Flechazo@548926
    driver-class-name: com.mysql.cj.jdbc.Driver